Sonar will not break the build
Due to some issues with the authorization token sonarcloud fails with
`ERROR: Error during SonarQube Scanner execution
ERROR: Not authorized. Please check the properties sonar.login and sonar.password.`
https://travis-ci.community/t/sonarcloud-fails-to-authorize/5845